import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SidebarHandler from "./_components/modules/Sidebar/SidebarHandler";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.className}  min-h-screen bg-white-smoke max-w-screen box-border w-screen`}
            >
                <SidebarHandler>{children}</SidebarHandler>
            </body>
        </html>
    );
}
